# Generated by Django 4.2.16 on 2026-08-26 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Bonafide Certificate Workflow"', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Purpose and scope of this workflow.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive workflows cannot be assigned to new service categories.')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Reserved for future versioning. Increment when stages change significantly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'db_table': 'workflows_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name shown to users, e.g. "Verification"', max_length=100)),
                ('code', models.CharField(help_text='Machine-readable slug used in WorkflowEngine logic, e.g. "VERIFICATION"', max_length=30)),
                ('description', models.TextField(blank=True, help_text='What happens during this stage. Shown in accountability timeline.')),
                ('order', models.PositiveSmallIntegerField(help_text='Display/progression order within the workflow. Lower = earlier.')),
                ('is_initial', models.BooleanField(default=False, help_text='Exactly one stage per workflow should be marked initial.')),
                ('is_terminal', models.BooleanField(default=False, help_text='Terminal stages mark the end of a workflow (resolved or rejected).')),
                ('is_rejection', models.BooleanField(default=False, help_text='Terminal stage specifically representing a rejected/declined outcome.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=15)),
                ('allowed_next_stages', models.ManyToManyField(blank=True, help_text='Stages that this stage may legally transition to. Empty for terminal stages.', related_name='reachable_from', to='workflows.workflowstage')),
                ('responsible_department', models.ForeignKey(help_text='Staff from this department can act on requests in this stage.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_stages', to='departments.department')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'verbose_name_plural': 'Workflow Stages',
                'db_table': 'workflows_stage',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'code'), ('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_hours', models.DecimalField(decimal_places=2, help_text='Maximum hours a request should remain in this stage.', max_digits=6)),
                ('warning_threshold_pct', models.PositiveSmallIntegerField(default=75, help_text='Percentage of target_hours elapsed before risk = warning. Default 75%.')),
                ('critical_threshold_pct', models.PositiveSmallIntegerField(default=90, help_text='Percentage of target_hours elapsed before risk = critical. Default 90%.')),
                ('stage', models.OneToOneField(help_text='Each stage has at most one SLA configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='sla_config', to='workflows.workflowstage')),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
                'db_table': 'workflows_sla_configuration',
            },
        ),
    ]
