# Generated by Django 4.2.16 on 2026-08-26 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text='True for the active assignment. False for historical records.')),
                ('note', models.TextField(blank=True, help_text='Reason for assignment or reassignment.')),
                ('assigned_by', models.ForeignKey(help_text='Who made this assignment. Null if auto-assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='The staff member currently responsible.', limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
