# Generated by Django 4.2.16 on 2026-08-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='service_requests.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['request', 'is_current'], name='idx_assignment_current'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_to', 'is_current'], name='idx_assignment_staff'),
        ),
    ]
