# Generated by Django 4.2.16 on 2026-08-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('STAGE_UPDATE', 'Stage Updated'), ('REQUEST_ASSIGNED', 'Request Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('REQUEST_RESOLVED', 'Request Resolved'), ('REQUEST_REJECTED', 'Request Rejected'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACH', 'SLA Breached'), ('GENERAL', 'General')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, help_text='The related request. Null for system-wide notifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='idx_notif_unread')],
            },
        ),
    ]
