# Generated by Django 4.2.16 on 2026-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_channels',
            field=models.JSONField(blank=True, default=dict, help_text='Simulated multi-channel delivery audit: in_app, email, sms, erp.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STAGE_UPDATE', 'Stage Updated'), ('REQUEST_ASSIGNED', 'Request Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('REQUEST_RESOLVED', 'Request Resolved'), ('REQUEST_REJECTED', 'Request Rejected'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACH', 'SLA Breached'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('GENERAL', 'General')], max_length=25),
        ),
    ]
