# Generated by Django 4.2.16 on 2026-08-26 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text='Machine-readable key, e.g. "purpose_of_certificate". Used as the key in ServiceRequest.dynamic_fields_data JSON.', max_length=50)),
                ('field_label', models.CharField(help_text='Display label shown to the student, e.g. "Purpose of Certificate"', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Dropdown Select'), ('date', 'Date Picker'), ('number', 'Number Input'), ('checkbox', 'Checkbox Group')], default='text', max_length=10)),
                ('options_json', models.JSONField(blank=True, help_text='For select/checkbox types. Format: [{"value": "...", "label": "..."}]', null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the category form. Lower = shown first.')),
                ('help_text', models.CharField(blank=True, help_text='Hint shown below the field to guide the student.', max_length=200)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for text/textarea inputs.', max_length=100)),
            ],
            options={
                'verbose_name': 'Dynamic Field Schema',
                'verbose_name_plural': 'Dynamic Field Schemas',
                'db_table': 'services_dynamic_field',
                'ordering': ['service_category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Academic", "Infrastructure"', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown to students when they hover/select this area.')),
                ('icon_key', models.CharField(blank=True, help_text='Frontend icon identifier, e.g. "graduation-cap", "wifi", "book"', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on the student request creation page.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'db_table': 'services_area',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Bonafide Certificate", "Wi-Fi Issue"', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Shown to students to help them choose the right category.')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Default priority assigned to new requests in this category.', max_length=10)),
                ('requires_attachment', models.BooleanField(default=False, help_text='If True, at least one attachment is required at request creation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owning_department', models.ForeignKey(help_text='Primary department responsible. Determines initial routing.', on_delete=django.db.models.deletion.PROTECT, related_name='service_categories', to='departments.department')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='services.servicearea')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'services_category',
                'ordering': ['service_area', 'name'],
            },
        ),
    ]
