# Generated by Django 4.2.16 on 2026-08-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='workflow',
            field=models.ForeignKey(help_text='The workflow that all requests in this category follow.', on_delete=django.db.models.deletion.PROTECT, related_name='service_categories', to='workflows.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='dynamicfieldschema',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='services.servicecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='servicecategory',
            unique_together={('service_area', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicfieldschema',
            unique_together={('service_category', 'field_key')},
        ),
    ]
