# Generated by Django 4.2.16 on 2026-08-26 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('STAGE_TRANSITION', 'Stage Transition'), ('STAGE_REJECTED', 'Request Rejected'), ('ASSIGNMENT', 'Assignment'), ('REASSIGNMENT', 'Reassignment'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded'), ('STATUS_CHANGED', 'Status Changed'), ('ON_HOLD', 'Placed On Hold'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved'), ('SLA_BREACHED', 'SLA Breached')], help_text='Machine-readable action type for filtering and display.', max_length=30)),
                ('description', models.TextField(help_text='Human-readable explanation of what happened and why. This is the explainability layer — always write something meaningful.')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Machine-readable context: stage names, durations, user IDs, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_student_visible', models.BooleanField(default=True, help_text='Internal-only audit entries (e.g. system events) are hidden from students.')),
                ('actor', models.ForeignKey(help_text='User who performed this action. Null for system-generated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Record',
                'verbose_name_plural': 'Audit Records',
                'db_table': 'audit_records',
                'ordering': ['request', 'timestamp'],
            },
        ),
    ]
