# Generated by Django 4.2.16 on 2026-08-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_requests', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='service_requests.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='auditrecord',
            index=models.Index(fields=['request', 'timestamp'], name='idx_audit_request_time'),
        ),
        migrations.AddIndex(
            model_name='auditrecord',
            index=models.Index(fields=['request', 'is_student_visible'], name='idx_audit_visibility'),
        ),
    ]
