# Generated by Django 4.2.16 on 2026-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='action',
            field=models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('STAGE_TRANSITION', 'Stage Transition'), ('STAGE_REJECTED', 'Request Rejected'), ('ASSIGNMENT', 'Assignment'), ('REASSIGNMENT', 'Reassignment'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded'), ('STATUS_CHANGED', 'Status Changed'), ('ON_HOLD', 'Placed On Hold'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved'), ('SLA_BREACHED', 'SLA Breached'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted')], help_text='Machine-readable action type for filtering and display.', max_length=30),
        ),
    ]
