# Generated by Django 4.2.16 on 2026-08-26 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(help_text='Human-readable identifier, e.g. REQ-2026-00042', max_length=20, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(help_text='Full description from the student.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', help_text='Coarse lifecycle status. Fine position = current_stage.', max_length=15)),
                ('dynamic_fields_data', models.JSONField(blank=True, default=dict, help_text='Values captured from DynamicFieldSchema at creation (Q1: creation-only).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set when request reaches a terminal stage.', null=True)),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the current_stage was entered. Used for live SLA calculation.')),
                ('current_stage', models.ForeignKey(help_text='Current stage in the workflow. Used for SLA calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_requests', to='workflows.workflowstage')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.servicecategory')),
                ('student', models.ForeignKey(help_text='Only student-role users can own requests.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Snapshot of the workflow at creation time.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflows.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entered_at', models.DateTimeField(help_text='When the request entered this stage.')),
                ('exited_at', models.DateTimeField(blank=True, help_text='When the request left this stage. NULL = still in this stage.', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Pre-computed on exit: (exited_at - entered_at) in minutes.', null=True)),
                ('transition_note', models.TextField(blank=True, help_text='Optional note recorded when transitioning stages.')),
                ('sla_breached', models.BooleanField(default=False, help_text='True if duration_minutes exceeded the stage SLA target.')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='service_requests.servicerequest')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='workflows.workflowstage')),
                ('transitioned_by', models.ForeignKey(help_text='Staff member who triggered this transition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Stage History',
                'verbose_name_plural': 'Request Stage Histories',
                'db_table': 'service_request_stage_history',
                'ordering': ['request', 'entered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['student'], name='idx_request_student'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['current_stage', 'stage_entered_at'], name='idx_request_sla'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_request_status'),
        ),
        migrations.AddIndex(
            model_name='requeststagehistory',
            index=models.Index(fields=['request', 'entered_at'], name='idx_history_request_time'),
        ),
    ]
