# Generated by Django 4.2.16 on 2026-09-29 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating from 1 to 5 stars.')),
                ('speed_rating', models.PositiveSmallIntegerField(default=5, help_text='Rating for resolution speed (1-5).')),
                ('helpfulness_rating', models.PositiveSmallIntegerField(default=5, help_text='Rating for staff helpfulness (1-5).')),
                ('clarity_rating', models.PositiveSmallIntegerField(default=5, help_text='Rating for process clarity (1-5).')),
                ('comment', models.TextField(blank=True, help_text='Optional review comment or feedback.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Aspect tags selected by the student (e.g. "Prompt Resolution", "Helpful Staff").')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(help_text='The service request this feedback belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='service_requests.servicerequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Feedback',
                'verbose_name_plural': 'Request Feedbacks',
                'db_table': 'service_request_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
