# Generated by Django 4.2.16 on 2026-08-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full department name, e.g. "Academic Section"', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code used in logic and seeding, e.g. "ACAD"', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text="Brief description of the department's function and services.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments are hidden from service category selectors.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, help_text='Department head (staff user). Receives escalation notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments_department',
                'ordering': ['name'],
            },
        ),
    ]
